import './globals.css';
import type { Metadata } from 'next';
import localFont from 'next/font/local';
import Navbar from './Navbar';

// Nur Geist Mono bleibt erhalten
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* Adobe Font-Link für Typekit */}
        <link rel="stylesheet" href="https://use.typekit.net/jwx2qsq.css" />
      </head>
      <body className={`${geistMono.variable}`}>
        <div style={{ position: 'relative', width: '100%', height: '100vh' }}>
          {/* <Navbar /> */}
          <main style={{ paddingTop: '0rem' }}>{children}</main>
        </div>
      </body>
    </html>
  );
}
